#!/usr/bin/env bash
# generate-prereq-map.sh — build lib/prereq-map.generated from skill sources (ADR-007)
# ─────────────────────────────────────────────────────────────────
# Replaces the 7-entry hardcoded PREREQ_MAP in hooks/sub-skill-gate with
# an autogenerated file derived from:
#
#   1. frontmatter `prerequisites:` (preferred, YAML list)
#   2. body `REQUIRED SUB-SKILL: <name>[, <name>...]` (fallback)
#
# Output format (identical to the array format sub-skill-gate uses):
#   siae-git-workflow=siae-git-env
#   siae-finishing-branch=siae-git-env,siae-git-workflow
#
# Run: bash lib/generate-prereq-map.sh
# Idempotent. Sorts lines for stable diffs.
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SKILLS_DIR="${REPO_ROOT}/skills"
OUT_FILE="${REPO_ROOT}/lib/prereq-map.generated"

if [ ! -d "$SKILLS_DIR" ]; then
    echo "error: $SKILLS_DIR not found" >&2
    exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Include "do not edit" marker in output. sub-skill-gate strips comments.
{
    echo "# DO NOT EDIT — generated by lib/generate-prereq-map.sh"
    echo "# Run the generator to refresh."
} > "$TMP"

# Read frontmatter prerequisites: list (YAML)
# Input: SKILL.md path
# Output on stdout: space-separated prereq names (or empty)
_parse_frontmatter_prereqs() {
    local file="$1"
    awk '
        BEGIN   { in_fm=0; in_prereq=0 }
        /^---[[:space:]]*$/ {
            if (in_fm == 0) { in_fm=1; next }
            else            { exit }
        }
        in_fm == 0 { next }
        /^prerequisites:/ {
            # Same-line value: `prerequisites: [a, b]`
            if (match($0, /\[[^]]*\]/)) {
                s=substr($0, RSTART+1, RLENGTH-2)
                gsub(/,/, " ", s)
                gsub(/"/, "", s)
                print s
                exit
            }
            in_prereq=1
            next
        }
        in_prereq == 1 {
            if ($0 ~ /^[[:space:]]*-[[:space:]]*[A-Za-z]/) {
                sub(/^[[:space:]]*-[[:space:]]*/, "")
                gsub(/[[:space:]]+$/, "")
                gsub(/"/, "")
                printf "%s ", $0
            } else if ($0 ~ /^[a-zA-Z]/) {
                # Next top-level key → prereq list ended
                exit
            }
        }
    ' "$file"
}

# Parse body line like: REQUIRED SUB-SKILL: siae-git-env
# Only the first occurrence of each skill name is kept. Ignores (opzionale).
_parse_body_prereqs() {
    local file="$1" line=""
    # Match four shapes (case-insensitive):
    #   REQUIRED SUB-SKILL: siae-x
    #   `REQUIRED SUB-SKILL: siae-x`        (backtick-wrapped)
    #   > REQUIRED SUB-SKILL: siae-x        (blockquote)
    #   Use REQUIRED SUB-SKILL: siae-x      (inline prose)
    # Tolerate no-match: grep exits non-zero → disable pipefail for this block.
    set +o pipefail
    line=$(grep -iE '^[`> ]*REQUIRED[[:space:]]+SUB[-_]SKILL:' "$file" 2>/dev/null | head -1 || true)
    set -o pipefail
    [ -z "$line" ] && return 0

    printf '%s\n' "$line" \
        | sed 's/^[`> ]*//' \
        | sed 's/`[[:space:]]*$//' \
        | sed 's/^[Rr][Ee][Qq][Uu][Ii][Rr][Ee][Dd][[:space:]]\{1,\}[Ss][Uu][Bb][-_][Ss][Kk][Ii][Ll][Ll]:[[:space:]]*//' \
        | sed 's/([^)]*)//g' \
        | sed 's/—.*//' \
        | sed 's/,[[:space:]]*/ /g' \
        | awk '{for(i=1;i<=NF;i++){gsub(/[^a-zA-Z0-9_-]/,"",$i); if($i) print $i}}' \
        | awk '!seen[$0]++' \
        | tr '\n' ' '
}

# Skill allow-list: downstream gates reject unknown names, so we never emit
# a prereq that does not correspond to a skill directory.
AVAILABLE_SKILLS=$(find "$SKILLS_DIR" -maxdepth 2 -name SKILL.md -exec dirname {} \; \
    | xargs -n1 basename | sort -u)

_is_known_skill() {
    printf '%s\n' "$AVAILABLE_SKILLS" | grep -qxF "$1"
}

# Curated overrides for skills whose body contains multiple REQUIRED SUB-SKILL
# declarations (some are output-instructions, not real prerequisites). When a
# skill is listed here the frontmatter still wins if present; otherwise this
# table replaces the first-body-hit heuristic.
#
# Source of truth: docs/plans/2026-04-25-anti-dilution-enforcement-design.md
# section "Skill → prereq attesi".
_curated_prereqs() {
    case "$1" in
        siae-git-workflow)     echo "siae-git-env" ;;
        siae-writing-plans)    echo "siae-brainstorming" ;;
        siae-executing-plans)  echo "siae-writing-plans" ;;
        siae-tdd)              echo "siae-brainstorming" ;;
        siae-iac)              echo "siae-brainstorming" ;;
        siae-data-engineering) echo "siae-brainstorming" ;;
        siae-frontend)         echo "siae-brainstorming" ;;
        siae-flutter)          echo "siae-brainstorming" ;;
        siae-robot-framework)  echo "siae-brainstorming" ;;
        siae-automation)       echo "siae-brainstorming" ;;
        siae-nr-test-flows)    echo "siae-brainstorming" ;;
        siae-qa)               echo "siae-brainstorming" ;;
        siae-blind-review)     echo "siae-finishing-branch" ;;
        siae-finishing-branch) echo "siae-git-env,siae-git-workflow" ;;
        # Explicit empty: these skills have noisy body REQUIRED SUB-SKILL
        # entries that are output-next-step reminders, not inputs. They are
        # entry points in the SDLC flow (no prerequisite invocation).
        siae-brainstorming)    echo "NONE" ;;
        siae-onboarding)       echo "NONE" ;;
        *) echo "" ;;
    esac
}

for skill_md in "$SKILLS_DIR"/*/SKILL.md; do
    skill_name=$(basename "$(dirname "$skill_md")")

    # 1. frontmatter (preferred — explicit author intent)
    prereqs=$(_parse_frontmatter_prereqs "$skill_md" | tr -s '[:space:]' ' ' | sed 's/^ *//;s/ *$//')

    # 2. curated override (for skills with noisy body text)
    curated_override=""
    if [ -z "$prereqs" ]; then
        curated=$(_curated_prereqs "$skill_name")
        if [ "$curated" = "NONE" ]; then
            # Explicit entry point — skip this skill entirely.
            continue
        elif [ -n "$curated" ]; then
            prereqs=$(echo "$curated" | tr ',' ' ')
            curated_override="yes"
        fi
    fi

    # 3. body REQUIRED SUB-SKILL (only if no frontmatter AND no curated override)
    if [ -z "$prereqs" ] && [ -z "$curated_override" ]; then
        prereqs=$(_parse_body_prereqs "$skill_md" | tr -s '[:space:]' ' ' | sed 's/^ *//;s/ *$//')
    fi

    [ -z "$prereqs" ] && continue

    # Filter to known skills + drop cross-cutting non-sequential prereqs.
    # siae-verification is invoked AFTER the skill (closing evidence), not
    # before — SKILL.md authors use `REQUIRED SUB-SKILL: siae-verification`
    # as a post-condition reminder. sub-skill-gate treats PREREQ_MAP as
    # sequential (must invoke BEFORE), so including verification would
    # deadlock almost every skill.
    CROSS_CUTTING="siae-verification siae-retrospective"
    filtered=""
    for p in $prereqs; do
        if ! _is_known_skill "$p"; then continue; fi
        skip=0
        for cc in $CROSS_CUTTING; do
            [ "$p" = "$cc" ] && skip=1 && break
        done
        [ "$skip" = "1" ] && continue
        case ",${filtered}," in
            *",${p},"*) ;;  # already present
            *) filtered="${filtered:+${filtered},}${p}" ;;
        esac
    done

    [ -z "$filtered" ] && continue
    printf '%s=%s\n' "$skill_name" "$filtered" >> "$TMP"
done

# Sort entries (skip header lines)
{
    grep '^#' "$TMP"
    grep -v '^#' "$TMP" | grep -v '^$' | sort -u
} > "${OUT_FILE}.tmp" && mv "${OUT_FILE}.tmp" "$OUT_FILE"

ENTRY_COUNT=$(grep -vc '^#\|^$' "$OUT_FILE" || true)
echo "generated $OUT_FILE with $ENTRY_COUNT entries"
