#!/usr/bin/env python3
"""migrate_jest_to_vitest.py - Atomic Jest -> Vitest migration (Phase 4b).

Reads strategy.json for migrating workspaces, then per-workspace:
  1. dirty-tree refuse
  2. snapshot files
  3. translate jest.config.* -> vitest.config.ts
  4. rewrite package.json (scripts + devDeps)
  5. codemod test files (21 token rewrites, no-rewrite for requireActual)
  6. rename jest.setup.* -> vitest.setup.*
  7. install (per-PM)
  8. smoke verify (npx vitest run)
  9. commit or rollback

Exit codes:
  0 = ok
  1 = refused / install failed
  2 = verification failed (snapshot restored)
  4 = noop (no migrating workspaces or opt-out)

CLI: python3 migrate_jest_to_vitest.py <repo_path>
Opt-out: CC_DISABLE_JEST_MIGRATION=1
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

ASSETS = (
    Path(__file__).resolve().parent.parent
    / "assets"
    / "vitest-jest-compat.json"
)

JEST_CONFIG_NAMES = (
    "jest.config.ts", "jest.config.js", "jest.config.mjs", "jest.config.cjs",
)
JEST_SETUP_NAMES = (
    "jest.setup.ts", "jest.setup.js", "jest.setup.mjs",
    "setupTests.ts", "setupTests.js",
)
SKIP_DIRS = {
    "node_modules", ".git", "dist", "build", ".venv",
    "target", "coverage", ".code-coverage",
}
REMOVE_DEVDEPS = {
    "jest", "@types/jest", "ts-jest", "babel-jest", "@swc/jest",
    "jest-environment-jsdom", "jest-environment-node",
    "jest-config", "jest-cli", "@jest/globals",
}

VITEST_CONFIG_TEMPLATE = '''import {{ defineConfig }} from 'vitest/config';

// Generated by code-coverage skill Phase 4b (Jest -> Vitest migration).
// Review and adapt as needed.
export default defineConfig({{
{alias_block}  test: {{
    environment: '{env}',
    globals: true,
{setup_block}    coverage: {{
      provider: 'v8',
      reporter: ['text', 'json-summary'],
    }},
  }},
}});
'''


_COMPAT_CACHE: dict | None = None


def _load_compat() -> dict:
    global _COMPAT_CACHE
    if _COMPAT_CACHE is None:
        _COMPAT_CACHE = json.loads(ASSETS.read_text(encoding="utf-8"))
    return _COMPAT_CACHE


# ─── Codemod core ─────────────────────────────────────────────────────────

def codemod_text(text: str) -> tuple[str, list[str], list[str]]:
    """Apply token rewrites + no-rewrite flagging + import injection.

    Returns (transformed_text, warnings, manual_review_entries).
    """
    compat = _load_compat()
    rewrites = compat["api_migration_map"]["rewrites"]
    no_rewrite = set(compat["api_migration_map"]["no_rewrite_tokens"])
    manual_triggers = compat["api_migration_map"]["manual_review_triggers"]

    warnings: list[str] = []
    manual: list[str] = []

    # Detect manual review triggers BEFORE rewriting
    for trig in manual_triggers:
        if trig in text:
            manual.append(f"manual-review:{trig}")

    out = text

    # Strip @jest/globals import lines
    out = re.sub(
        r"^import\s+[^;]+from\s+['\"]@jest/globals['\"];\s*\n",
        "",
        out,
        flags=re.MULTILINE,
    )

    # @testing-library/jest-dom + /extend-expect → /vitest
    # First handle /extend-expect explicit suffix
    out = out.replace(
        "@testing-library/jest-dom/extend-expect",
        "@testing-library/jest-dom/vitest",
    )
    # Then bare @testing-library/jest-dom → /vitest (idempotent guard)
    out = re.sub(
        r"@testing-library/jest-dom(?!/vitest)(?!/extend-expect)",
        "@testing-library/jest-dom/vitest",
        out,
    )

    # Token rewrites (skip no_rewrite, word-boundary safe)
    for rule in rewrites:
        from_tok = rule["from"]
        # Match form jest.X( — strip the trailing ( for the no_rewrite check
        base = from_tok.rstrip("(")
        if base in no_rewrite:
            continue
        # Boundary-safe: not preceded by word char, ., or $
        pat = r"(?<![\w.$])" + re.escape(from_tok)
        out = re.sub(pat, rule["to"], out)

    # Inject `import { vi } from 'vitest';` if vi.* used and no existing import
    if re.search(r"(?<![\w.$])vi\.", out) and not re.search(
        r"from\s+['\"]vitest['\"]", out,
    ):
        out = "import { vi } from 'vitest';\n" + out

    return out, warnings, manual


# ─── Jest config translation ──────────────────────────────────────────────

def translate_jest_config_to_vitest(
    jest_cfg: Path, ws_dir: Path,
) -> tuple[str, list[str]]:
    text = _read_text(jest_cfg)
    unmapped: list[str] = []

    compat = _load_compat()
    manual_review_keys = compat["api_migration_map"]["config_keys_manual_review"]
    for key in manual_review_keys:
        if re.search(rf"\b{re.escape(key)}\s*:", text):
            unmapped.append(f"{key}: no direct Vitest equivalent, manual review")

    env = "node"
    m = re.search(r"testEnvironment\s*:\s*['\"](\w+)['\"]", text)
    if m and m.group(1) == "jsdom":
        env = "jsdom"

    aliases: dict[str, str] = {}
    m = re.search(r"moduleNameMapper\s*:\s*\{([^}]+)\}", text, re.DOTALL)
    if m:
        for k, v in re.findall(
            r"['\"]([^'\"]+)['\"]\s*:\s*['\"]([^'\"]+)['\"]",
            m.group(1),
        ):
            ck = re.sub(r"^\^?|\$?$|\(\.\*\)", "", k).strip("/")
            aliases[ck] = v.replace("<rootDir>/", "").replace("$1", "")

    alias_block = ""
    if aliases:
        alias_block = "  resolve: {\n    alias: {\n"
        for k, v in aliases.items():
            alias_block += f"      {json.dumps(k)}: {json.dumps(v)},\n"
        alias_block += "    },\n  },\n"

    setup_files: list[str] = []
    m = re.search(r"\bsetupFiles\s*:\s*\[([^\]]+)\]", text, re.DOTALL)
    if m:
        setup_files = re.findall(r"['\"]([^'\"]+)['\"]", m.group(1))
    setup_block = ""
    if setup_files:
        renamed = [s.replace("jest.setup", "vitest.setup") for s in setup_files]
        setup_block = f"    setupFiles: {json.dumps(renamed)},\n"

    content = VITEST_CONFIG_TEMPLATE.format(
        alias_block=alias_block,
        env=env,
        setup_block=setup_block,
    )
    return content, unmapped


# ─── package.json rewrite ─────────────────────────────────────────────────

def rewrite_package_json(pkg_path: Path) -> dict:
    pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    report = {"scripts_changed": [], "devdeps_removed": [], "devdeps_added": []}

    scripts = pkg.get("scripts", {})
    for name, script in list(scripts.items()):
        if not isinstance(script, str):
            continue
        new_script = re.sub(r"\bjest\s+--watch(?:All)?\b", "vitest", script)
        new_script = re.sub(
            r"\bjest\s+--coverage\b",
            "vitest run --coverage",
            new_script,
        )
        new_script = re.sub(
            r"(^|\s|&&\s*)jest($|\s)",
            r"\1vitest run\2",
            new_script,
        )
        new_script = re.sub(r"\s+", " ", new_script).strip()
        if new_script != script:
            scripts[name] = new_script
            report["scripts_changed"].append(name)
    if scripts:
        pkg["scripts"] = scripts

    dev = pkg.get("devDependencies", {})
    for dep in list(dev.keys()):
        if dep in REMOVE_DEVDEPS:
            del dev[dep]
            report["devdeps_removed"].append(dep)
        elif dep.startswith("jest-") and dep not in {"jest-junit"}:
            del dev[dep]
            report["devdeps_removed"].append(dep)
    for added in ("vitest", "@vitest/coverage-v8"):
        if added not in dev:
            dev[added] = "^1.6.0"
            report["devdeps_added"].append(added)

    all_deps = {**(pkg.get("dependencies") or {}), **dev}
    frontend_markers = {
        "react", "vue", "@angular/core", "svelte",
        "@testing-library/react", "@testing-library/vue",
    }
    if any(k in all_deps for k in frontend_markers) and "jsdom" not in dev:
        dev["jsdom"] = "^24.0.0"
        report["devdeps_added"].append("jsdom")

    if dev:
        pkg["devDependencies"] = dev
    if "jest" in pkg:
        del pkg["jest"]

    pkg_path.write_text(
        json.dumps(pkg, indent=2) + "\n",
        encoding="utf-8",
    )
    return report


# ─── Setup file rename ────────────────────────────────────────────────────

def rename_setup_files(ws_dir: Path) -> list[str]:
    renamed: list[str] = []
    for name in JEST_SETUP_NAMES:
        src = ws_dir / name
        if not src.is_file():
            continue
        text = _read_text(src)
        new_text, _, _ = codemod_text(text)
        dst = ws_dir / "vitest.setup.ts"
        if dst.exists() and dst != src:
            renamed.append(f"CONFLICT:{src.name} -> vitest.setup.ts (target exists)")
            continue
        dst.write_text(new_text, encoding="utf-8")
        if src != dst:
            src.unlink()
        renamed.append(f"{src.name} -> vitest.setup.ts")
    return renamed


# ─── PM detection + per-PM matrix ─────────────────────────────────────────

def detect_pm(ws_dir: Path) -> str:
    if (ws_dir / ".yarnrc.yml").is_file() and (ws_dir / "yarn.lock").is_file():
        return "yarn-berry"
    if (ws_dir / "pnpm-lock.yaml").is_file():
        return "pnpm"
    if (ws_dir / "yarn.lock").is_file():
        return "yarn"
    if (ws_dir / "bun.lockb").is_file():
        return "bun"
    return "npm"


def install_cmd_for(pm: str) -> list[str]:
    return {
        "npm": ["npm", "install"],
        "pnpm": ["pnpm", "install"],
        "yarn": ["yarn", "install"],
        "yarn-berry": ["yarn", "install"],
        "bun": ["bun", "install"],
    }[pm]


def rollback_install_cmd_for(pm: str) -> list[str]:
    return {
        "npm": ["npm", "ci"],
        "pnpm": ["pnpm", "install", "--frozen-lockfile"],
        "yarn": ["yarn", "install", "--frozen-lockfile"],
        "yarn-berry": ["yarn", "install", "--immutable"],
        "bun": ["bun", "install", "--frozen-lockfile"],
    }[pm]


def lockfile_for(pm: str) -> list[str]:
    return {
        "npm": ["package-lock.json"],
        "pnpm": ["pnpm-lock.yaml"],
        "yarn": ["yarn.lock"],
        "yarn-berry": ["yarn.lock", ".yarnrc.yml"],
        "bun": ["bun.lockb"],
    }[pm]


# ─── Helpers ─────────────────────────────────────────────────────────────

def _read_text(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def check_clean_tree(repo: Path, touched: list[Path]) -> tuple[bool, str]:
    """Returns (is_clean, diagnostic_message). True if no git or no dirty."""
    if not (repo / ".git").is_dir():
        return True, ""
    rel: list[str] = []
    for p in touched:
        if p.exists():
            try:
                rel.append(str(p.relative_to(repo)))
            except ValueError:
                continue
    if not rel:
        return True, ""
    try:
        r = subprocess.run(
            ["git", "-C", str(repo), "status", "--porcelain", "--"] + rel,
            capture_output=True, text=True, timeout=10,
        )
        return (not r.stdout.strip(), r.stdout)
    except subprocess.SubprocessError as e:
        return True, str(e)


def snapshot_files(repo: Path, files: list[Path]) -> Path:
    snap = repo / ".code-coverage" / "migration-snapshot"
    snap.mkdir(parents=True, exist_ok=True)
    for f in files:
        if not f.is_file():
            continue
        try:
            rel = f.relative_to(repo)
        except ValueError:
            continue
        dst = snap / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, dst)
    return snap


def restore_snapshot(repo: Path) -> None:
    snap = repo / ".code-coverage" / "migration-snapshot"
    if not snap.is_dir():
        return
    for src in snap.rglob("*"):
        if src.is_file():
            rel = src.relative_to(snap)
            dst = repo / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)


def list_test_files(ws: Path) -> list[Path]:
    out: list[Path] = []
    for pat in (
        "**/*.test.ts", "**/*.test.tsx", "**/*.test.js", "**/*.test.jsx",
        "**/*.spec.ts", "**/*.spec.js",
    ):
        for f in ws.glob(pat):
            if any(part in SKIP_DIRS for part in f.parts):
                continue
            out.append(f)
    return out


def smoke_test(ws: Path, pm: str, timeout: int = 120) -> tuple[bool, str]:
    if pm == "pnpm":
        cmd = ["pnpm", "exec", "vitest", "run", "--reporter=basic", "--no-coverage"]
    elif pm in ("yarn", "yarn-berry"):
        cmd = ["yarn", "vitest", "run", "--reporter=basic", "--no-coverage"]
    elif pm == "bun":
        cmd = ["bunx", "vitest", "run", "--reporter=basic", "--no-coverage"]
    else:
        cmd = ["npx", "vitest", "run", "--reporter=basic", "--no-coverage"]
    try:
        r = subprocess.run(
            cmd, cwd=str(ws),
            capture_output=True, text=True, timeout=timeout,
        )
        if r.returncode == 0:
            return True, ""
        return False, (r.stderr or r.stdout or "")[-2000:]
    except subprocess.TimeoutExpired:
        return False, f"timed out after {timeout}s"
    except FileNotFoundError as e:
        return False, str(e)


def find_jest_config(ws: Path) -> Path | None:
    for n in JEST_CONFIG_NAMES:
        p = ws / n
        if p.is_file():
            return p
    return None


def _migrating_workspaces(repo: Path) -> list[str]:
    s_path = repo / ".code-coverage" / "strategy.json"
    if not s_path.is_file():
        return []
    try:
        s = json.loads(s_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    fw = s.get("framework_by_workspace", {}) or {}
    return [ws for ws, info in fw.items() if info.get("migrate") is True]


# ─── Workspace migration ──────────────────────────────────────────────────

def migrate_workspace(repo: Path, ws_rel: str) -> dict:
    ws = repo if ws_rel == "." else repo / ws_rel
    pm = detect_pm(ws)
    jest_cfg = find_jest_config(ws)
    vitest_cfg = ws / "vitest.config.ts"

    touched: list[Path] = [ws / "package.json"]
    if jest_cfg:
        touched.append(jest_cfg)
    touched.extend(
        [ws / n for n in JEST_SETUP_NAMES if (ws / n).is_file()],
    )
    touched.extend(
        [ws / lf for lf in lockfile_for(pm) if (ws / lf).is_file()],
    )
    touched.extend(list_test_files(ws))

    clean, dirty_msg = check_clean_tree(repo, touched)
    if not clean:
        return {
            "workspace": ws_rel,
            "status": "refused",
            "reason": "dirty-working-tree",
            "detail": dirty_msg,
        }

    snapshot_files(repo, touched)

    report: dict[str, Any] = {
        "workspace": ws_rel, "status": "ok", "pm": pm,
        "files": {"transformed": [], "renamed": [], "manual_review": []},
        "unmapped_keys": [],
    }

    try:
        if jest_cfg and not vitest_cfg.is_file():
            content, unmapped = translate_jest_config_to_vitest(jest_cfg, ws)
            vitest_cfg.write_text(content, encoding="utf-8")
            report["unmapped_keys"] = unmapped

        if (ws / "package.json").is_file():
            report["package_json"] = rewrite_package_json(ws / "package.json")

        for f in list_test_files(ws):
            text = _read_text(f)
            new_text, _, manual = codemod_text(text)
            if new_text != text:
                f.write_text(new_text, encoding="utf-8")
                rel = str(f.relative_to(repo))
                report["files"]["transformed"].append(rel)
                if manual:
                    report["files"]["manual_review"].extend(
                        f"{rel}: {m}" for m in manual
                    )

        report["files"]["renamed"] = rename_setup_files(ws)

        if jest_cfg and vitest_cfg.is_file():
            vitest_content = _read_text(vitest_cfg)
            if "defineConfig" in vitest_content and "export default" in vitest_content:
                jest_cfg.unlink()
                report["files"]["renamed"].append(f"deleted:{jest_cfg.name}")

        try:
            r = subprocess.run(
                install_cmd_for(pm), cwd=str(ws),
                capture_output=True, text=True, timeout=300,
            )
            report["install"] = {"cmd": install_cmd_for(pm), "exit_code": r.returncode}
            if r.returncode != 0:
                report["status"] = "install-failed"
                report["install"]["stderr_tail"] = (r.stderr or "")[-1000:]
                return report
        except subprocess.TimeoutExpired:
            report["status"] = "install-timeout"
            return report
        except FileNotFoundError:
            report["install"] = {"skipped": "pm-binary-not-found"}
            return report

        ok, tail = smoke_test(ws, pm)
        if ok:
            report["verified"] = True
        else:
            report["verified"] = False
            report["status"] = "verification-failed"
            report["verification_tail"] = tail

    except Exception as e:
        report["status"] = "internal-error"
        report["error"] = str(e)

    return report


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("repo_path")
    args = ap.parse_args()
    repo = Path(args.repo_path).resolve()

    if os.environ.get("CC_DISABLE_JEST_MIGRATION") == "1":
        print(json.dumps({
            "status": "skipped",
            "reason": "CC_DISABLE_JEST_MIGRATION=1",
        }))
        return 4

    workspaces = _migrating_workspaces(repo)
    if not workspaces:
        print(json.dumps({
            "status": "noop",
            "reason": "no workspaces with migrate=true",
        }))
        return 4

    started = time.time()
    overall: dict = {"started_at": started, "workspaces": []}
    failed_verification = False
    for ws in workspaces:
        r = migrate_workspace(repo, ws)
        overall["workspaces"].append(r)
        if r["status"] == "verification-failed":
            failed_verification = True

    overall["elapsed_sec"] = round(time.time() - started, 2)
    out_path = repo / ".code-coverage" / "migration-report.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(overall, indent=2), encoding="utf-8")

    print(json.dumps(overall, indent=2))

    if failed_verification:
        restore_snapshot(repo)
        # Re-install with frozen-lockfile to keep node_modules consistent with
        # restored package.json + lockfile. Per workspace that had been
        # touched (status != "refused" / "noop"). Best-effort: failures here
        # are logged but do not change the exit code (2 already signals
        # verification-failed + restored).
        for r in overall["workspaces"]:
            if r.get("status") in ("refused", "noop"):
                continue
            ws_rel = r.get("workspace", ".")
            ws_path = repo if ws_rel == "." else repo / ws_rel
            pm = r.get("pm") or detect_pm(ws_path)
            try:
                subprocess.run(
                    rollback_install_cmd_for(pm),
                    cwd=str(ws_path),
                    capture_output=True, text=True, timeout=300,
                    check=False,
                )
            except (subprocess.SubprocessError, FileNotFoundError, KeyError):
                # rollback_install_cmd_for raises KeyError on unknown pm;
                # SubprocessError on timeout; FileNotFoundError on missing
                # pm binary. All non-fatal — snapshot is already restored.
                pass
        return 2
    if any(
        r["status"] in (
            "refused", "install-failed", "install-timeout", "internal-error",
        )
        for r in overall["workspaces"]
    ):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
