#!/usr/bin/env bash
# build_perf_corpus.sh — Wave 1 follow-up task-16
# Genera tests/fixtures/perf_corpus_200k/ con ~200k LOC synthetic
# multi-stack (TS+Java+Python+SQL+TF) per benchmark P95.
# Idempotente: re-run produce identico filesystem state.
set -euo pipefail

OUT="${OUT:-tests/fixtures/perf_corpus_200k}"
mkdir -p "$OUT"

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing: $1" >&2; exit 1; }
}
require python3

cat > "$OUT/manifest.yaml" <<'EOF'
# Perf corpus mock manifest — synthetic, NO broadcasting reale (ADR-004)
generator: scripts/build_perf_corpus.sh
loc_target:
  typescript: 200000
  java: 50000
  python: 30000
  sql: 10000
  terraform: 10000
EOF

python3 - <<'PY'
"""Generator deterministico (no random) per idempotenza."""
from pathlib import Path

OUT = Path("tests/fixtures/perf_corpus_200k")

def gen_ts(i):
    return f"""// Module {i} synthetic
import {{ Database }} from './db';
export async function handler_{i}(req: any, res: any) {{
  const db = new Database();
  const rows = await db.query('SELECT * FROM tbl_{i} WHERE id = $1', [req.params.id]);
  return res.json(rows);
}}
"""

def gen_java(i):
    return f"""package it.siae.synthetic;
public class Handler{i} {{
  public String process(String input) {{ return input + "_{i}"; }}
}}
"""

def gen_py(i):
    return f"def handler_{i}(data):\n    return data + '_{i}'\n"

def gen_sql(i):
    return f"CREATE TABLE tbl_{i} (id INTEGER PRIMARY KEY);\n"

def gen_tf(i):
    return f'resource "aws_s3_bucket" "bucket_{i}" {{ bucket = "siae-syn-{i}" }}\n'

specs = [
    ("typescript", gen_ts, 1000, "ts"),
    ("java", gen_java, 500, "java"),
    ("python", gen_py, 1500, "py"),
    ("sql", gen_sql, 100, "sql"),
    ("terraform", gen_tf, 100, "tf"),
]
for kind, gen, count, ext in specs:
    d = OUT / kind
    d.mkdir(parents=True, exist_ok=True)
    for i in range(count):
        (d / f"mod_{i}.{ext}").write_text(gen(i))

print(f"Corpus built in {OUT}")
PY

# Add .gitignore inside corpus dir to exclude generated content (not committed)
cat > "$OUT/.gitignore" <<'EOF'
# Generated by scripts/build_perf_corpus.sh — exclude individual modules
typescript/
java/
python/
sql/
terraform/

# Commit only manifest + this gitignore
!manifest.yaml
!.gitignore
EOF

echo "Done. To run perf benchmark: pytest tests/test_review_evidence_perf.py -v -m slow"
